### ISSUE TITLE
Sessions missing from sqlsaturday #961

### ISSUE THREAD

**Issue by sqlworldwide** [andrekamman/sqlsathistory#1]
Few sessions are missing from SQL Saturday Albany #961.
Example:
https://www.sqlsaturday.com/961/Sessions/Details/sid/107240
https://www.sqlsaturday.com/961/Sessions/Details/sid/107233

**Comment by andrekamman** [comment]
Hi Taiob, 

Thank you for bringing this to my attention!

The raw data is unfortunately not the cleanest. (interesting for a Data Conference org but oh well...)
Some sessions, including the 2 sessions you mention are not available in the GuidebookXML data that this site is based on. 
(You can find the source data in the xml folder in this repo)

I've looked in the PASS data from their Speaker management system which also seems to have SQLSaturday information. And I can find your session there. But it doesn't have time and room information and the ID's don't match up, so it would be hard to merge those two sources into one (I'll take a closer look later but no promises)

There is also an issue with multiple speakers for one session for instance. The PASS data has it, but the Guidebook (SQLSat) data does not. I want to do an attempt to get that data from the PASS Source but have to find a good way to match up the sessions first.

If you want to keep a link alive to sessions you did that you can't find in this resource, your best alternative would be the PDF's that Ben Weissman provides. Here is the link to the PDF for the event in your example for instance. It seems to be complete:
http://newstarsofdata.com/sqlsaturday/0961.pdf

Hope this helps! 

Regards,

André

**Comment by sqlworldwide** [comment]
Hi Andre,Thank you so much. Taiob





 

    On Monday, January 4, 2021, 03:20:39 AM EST, André Kamman <notifications@github.com> wrote:  
 
 


Hi Taiob,

Thank you for bringing this to my attention!

The raw data is unfortunately not the cleanest. (interesting for a Data Conference org but oh well...)
Some sessions, including the 2 sessions you mention are not available in the GuidebookXML data that this site is based on.
(You can find the source data in the xml folder in this repo)

I've looked in the PASS data from their Speaker management system which also seems to have SQLSaturday information. And I can find your session there. But it doesn't have time and room information and the ID's don't match up, so it would be hard to merge those two sources into one (I'll take a closer look later but no promises)

There is also an issue with multiple speakers for one session for instance. The PASS data has it, but the Guidebook (SQLSat) data does not. I want to do an attempt to get that data from the PASS Source but have to find a good way to match up the sessions first.

If you want to keep a link alive to sessions you did that you can't find in this resource, your best alternative would be the PDF's that Ben Weissman provides. Here is the link to the PDF for the event in your example for instance. It seems to be complete:
http://newstarsofdata.com/sqlsaturday/0961.pdf

Hope this helps!

Regards,

André
